name: Streamlit Uptime Monitor

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  uptime-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Make script executable
        run: chmod +x scripts/uptime_check.sh

      - name: Run Uptime Check
        run: ./scripts/uptime_check.sh
