name: Streamlit Uptime Monitor

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  uptime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run uptime script
        run: |
          chmod +x scripts/uptime_check.sh
          ./scripts/uptime_check.sh
